const ubicaciones = [
    { value: "CM", label: "Consejo Municipal" },
    { value: "PM", label: "Personeria Municipal" },
    { value: "OACR",label: "Oficina Asesora de Comunicaciones y Relaciones" },
    { value: "AM", label: "Alcaldía Municipal" },
    { value: "OCDI",label: "Oficina Control Disciplinario Interno" },
    { value: "DA", label: "Despacho Alcaldía" },
    { value: "DAEC", label: "Departamento Administrativo de Evaluación y Control" },
    { value: "OES", label: "Oficina de Estadística-Sisbén" },
    { value: "S", label: "Sisbén" },
    { value: "OPE", label: "Oficina de Planeación Estratégica" },
    { value: "DP", label: "Despacho Planeación" },
    { value: "DAP", label: "Departamento Administrativo de Planeación" },
    { value: "CU", label: "Control Urbanístico" },
    { value: "OADC", label: "Oficina Asesora de Desarrollo Comunitario" },
    { value: "DDC", label: "Despacho Desarrollo Comunitario" },
    { value: "EF", label: "Ejecuciones Fiscales" },
    { value: "CaM", label: "Catrastro Municipal" },
    { value: "OI", label: "Oficina de Impuesto" },
    { value: "SH", label: "Secretaria de Hacienda" },
    { value: "SubH", label: "Subsecretaría de Hacienda" },
    { value: "P", label: "Planeación" },
    { value: "IC1", label: "Indistria y Comercio 1" },
    { value: "DF", label: "Dirección Financiera" },
    { value: "C", label: "Contabilidad" },
    { value: "SA", label: "Subsecretaría Ambiental" },
    { value: "DV", label: "Dirección de Vivienda" },
    { value: "DAP2", label: "Despacho Alcaldía Principal" },
    { value: "SI,A", label: "Secretaría de Infraestructura, Ambiente" },
    { value: "SE", label: "Secretaría de Educación" },
    { value: "DE", label: "Despacho Educación" },
    { value: "UAI", label: "Unidad de Atención Integral" },
    { value: "NE", label: "Núcleo Educativo" },
    { value: "CFMC", label: "Colegio Francisco María Cardona" },
    { value: "IP1", label: "Inspección Policía 1" },
    { value: "IP2", label: "Inspección de Policía 2" },
    { value: "IPE.A.P", label: "Inspección de Policía y E.A.P" },
    { value: "CSJ", label: "Corregidor San José" },
    { value: "CP", label: "Comisaría-Psicologo" },
    { value: "SGS", label: "Secretaría de Gobierno y Seguridad" },
    { value: "SGCM", label: "Subsecretaría de Gobierno - Centro Monitoreo" },
    { value: "CPOC", label: "Comando de Policía Obreros de Cristo" },
    { value: "CPOSJ", label: "Comando de Policía Corregimiento San José" },
    { value: "IA", label: "Infancía y Adolescencia" },
    { value: "LS", label: "La Sijin" },
    { value: "CTS", label: "Comisaría Trabajadora Social" },
    { value: "DG", label: "Despacho de Gobierno" },
    { value: "CG", label: "Comeger" },
    { value: "CJP", label: "Casa de Justicia y Paz" },
    { value: "OEV", label: "Oficina Enlace Victimas" },
    { value: "DSM", label: "Despacho Secretaría de Movilidad" },
    { value: "AT", label: "Agentes de Transito" },
    { value: "SFEP", label: "Subsecretaría de Familía y Entornos de Protección" },
    { value: "OEG", label: "Oficina de Equidad y Genero" },
    { value: "CF1", label: "Comisaría de Familia 1" },
    { value: "DPS", label: "Despacho Protección Social" },
    { value: "DAAM", label: "Dirección de Atención al Adulto Mayor" },
    { value: "SF", label: "Subsecretaría de Familia" },
    { value: "OSP", label: "Oficina de Salud Pública" },
    { value: "RS", label: "Regimen Subsidiado" },
    { value: "ICDI", label: "Inventario CDI" }, // Nota: Había un OCDI duplicado, asumí que este era diferente.
    { value: "SDC", label: "Subdirección de Contratación" },
    { value: "AC", label: "Archivo Central" },
    { value: "OGH", label: "Oficina de Gestión Humana" },
    { value: "OS", label: "Oficina de Sistemas" },
    { value: "DAGS", label: "Departamento Administrativo de Generación y Servicio" },
    { value: "SC", label: "Sistema de Calidad" },
    { value: "AM2", label: "Almacen Municipal" },
    { value: "GP", label: "Gestión Predial" },
    { value: "DDE", label: "Despacho de Desarrollo Económico" },
    { value: "OEE", label: "Oficina de Emprendimiento y Empleabilidad" },
    { value: "CAG", label: "Centro Agronegocios" },
    { value: "C1S", label: "Comisaría 1-Secretario" },
    { value: "CSPAP", label: "Comisaría Seccional Primera de La Ceja - Área de Psicología" },
    { value: "SDEC", label: " Secretaría(o) de Evaluació y Control" },
    { value: "ELRC", label: "Emisora Local Radio Capiro" },
    { value: "DDC2", label: "Director(a) de Comunicaciones" },
    { value: "CF2", label: "Comisaría de Familia 2" },
    { value: "CTO", label: "Contabilidad Técnico Operativo" },
    { value: "CF3", label: "Comisaría de Familia 3" },
    { value: "ACM", label: "Asocomunal de La Ceja" },
    { value: "COMD", label: "Comodato" },
    { value: "CRPB", label: "Corporación Rotario Para el Bienestar" },
    { value: "ITO", label: "Inventario Técnico Operativo" },
    { value: "BI", label: "Bodega Inservibles" },
    { value: "AJ1", label: "AsesorJuridico1" },
    { value: "AJ2", label: "AsesorJuridico2" },
    { value: "DPC", label: "Despacho Cultura" },
    { value: "TJDDA", label: "Teatro Juan de Dios Aranzazu" },
    { value: "BBM", label: "Biblioteca Municipal" },
    { value: "BBEP", label: "Biblioteca El Paraiso" },
    { value: "CFA", label: "Comisaría de Familia-Abogado" },
];

const opcionPorDefecto = { value: "", label: "Seleccione la Ubicación" };

      

ubicaciones.sort((a, b) => {
    // localeCompare es útil para ordenar cadenas que pueden tener acentos o caracteres especiales.
    return a.label.localeCompare(b.label);
});

export const DatosUbicacion = [opcionPorDefecto, ...ubicaciones];