export const RAM = [
    {value: "", label: "Seleccione capacidad de RAM"},
    {value: "2GB", label: "2GB"},
    {value: "4GB", label: "4GB"},
    {value: "6GB", label: "6GB" },
    {value: "8GB", label: "8GB"},
    {value: "10GB", label: "10GB"},
    {value: "12GB", label: "12GB"},
    {value: "16GB", label: "16GB"},
    {value: "20GB", label: "20GB"},
    {value: "24GB", label: "24GB"},
    {value: "32GB", label: "32GB"},
    {value: "36GB", label: "36GB"},
    {value: "40GB", label: "40GB"},
    {value: "44GB", label: "44GB"},
    {value: "48GB", label: "48GB"},
    {value: "52GB", label: "52GB"},
    
    {value: "64GB", label: "64GB"},
    {value: "68GB", label: "68GB"},
    {value: "72GB", label: "72GB"},
    {value: "80GB", label: "80GB"},
    
    {value: "128GB", label: "128GB"},
];