export const SistemaOperativo = [
    {value: "", label: "Seleccione sistema operativo"},
    {value: "Windows 7", label: "Windows 7"},
    {value: "Windows 7 Starter" , label: "Windows 7 Starter"},
    {value: "Windows 7 Home Basic", label: "Windows 7 Home Basic"},
    {value: "Windows 7 Home Premium", label: "Windows 7 Home Premium"},
    {value: "Windows 7 Professional", label: "Windows 7 Professional"},
    {value: "Windows 7 Ultimate", label: "Windows 7 Ultimate"},
    {value: "Windows 7 Enterprise", label: "Windows 7 Enterprise"},
    {value: "Windows 7 Home", label: "Windows 7 Home"},
    {value: "Windows 7 Pro", label: "Windows 7 Pro"},
    {value: "Windows 8", label: "Windows 8"},
    {value: "Windows 8 Pro", label: "Windows 8 Pro"},
    {value: "Windows 8 Enterprise", label: "Windows 8 Enterprise"},
    {value: "Windows 8.1", label: "Windows 8.1"},
    {value: "Windows 8.1 Pro", label: "Windows 8.1 Pro"},
    {value: "Windows 8.1 Enterprise", label: "Windows 8.1 Enterprise"},
   
    {value: "Windows 10", label: "Windows 10"},
    {value: "Windows 10 Pro", label: "Windows 10 Pro"},
    {value: "Windows 10 Enterprise", label: "Windows 10 Enterprise"},
    {value: "Windows 10 Home", label: "Windows 10 Home"},
    {value: "Windows 10 Education", label: "Windows 10 Education"},
    {value: "Windows 10 Pro Education", label: "Windows 10 Pro Education"},
    {value: "Windows 10 Pro for Workstations", label: "Windows 10 Pro for Workstations"},
    {value: "Windows 10 S", label: "Windows 10 S"},
    {value: "Windows 10X", label: "Windows 10X"},
    {value: "Windows 10 IoT", label: "Windows 10 IoT"},
    {value: "Windows 11", label: "Windows 11"},
    {value: "Windows 11 Pro", label: "Windows 11 Pro"},
    {value: "Windows 11 Enterprise", label: "Windows 11 Enterprise"},
    {value: "Windows 11 Home", label: "Windows 11 Home"},
    {value: "Windows 11 Education", label: "Windows 11 Education"},
    {value: "Windows 11 Pro Education", label: "Windows 11 Pro Education"},
    {value: "Windows 11 Pro for Workstations", label: "Windows 11 Pro for Workstations"},
    {value: "Windows 11 SE", label: "Windows 11 SE"},
    {value: "Windows 11 IoT", label: "Windows 11 IoT"},
    {value: "Windows 11X", label: "Windows 11X"},    
    {value: "Linux", label: "Linux"},
    {value: "Ubuntu", label: "Ubuntu"},
    {value: "Debian", label: "Debian"},
    {value: "Fedora", label: "Fedora"},
    {value: "CentOS", label: "CentOS"},
    {value: "Red Hat", label: "Red Hat"},
    {value: "Arch Linux", label: "Arch Linux"},
    {value: "Linux Mint", label: "Linux Mint"},
    {value: "MacOS", label: "MacOS"},
    {value: "Otros", label: "Otros"},
];