const LugarExcepcion = Object.freeze({
    GENERAL:'GENERAL',
    INFRESTRUCTURA:'INFRAESTRUCTURA',
    APLICACION:'APLICACION',
    DOMINIO:'DOMINIO',
    API:'API',
    DATO:'DATO',
    CONTROLADOR:'CONTROLADOR',
    SERVICIO:'SERVICIO',
    CORTETRANSVERSAL:'CORTETRANSVERSAL',
    REPOSITORIO:'REPOSITORIO',
    BASE_DE_DATOS:'BASE_DE_DATOS'});
module.exports = LugarExcepcion;
